//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfig) DeepCopyInto(out *AWSConfig) {
	*out = *in
	if in.AssumeRoleRequireExternalID != nil {
		in, out := &in.AssumeRoleRequireExternalID, &out.AssumeRoleRequireExternalID
		*out = new(bool)
		**out = **in
	}
	if in.AllowDirectSystemCredentials != nil {
		in, out := &in.AllowDirectSystemCredentials, &out.AllowDirectSystemCredentials
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfig.
func (in *AWSConfig) DeepCopy() *AWSConfig {
	if in == nil {
		return nil
	}
	out := new(AWSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationConfig) DeepCopyInto(out *AuthenticationConfig) {
	*out = *in
	if in.OpenID != nil {
		in, out := &in.OpenID, &out.OpenID
		*out = new(OpenIDConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(KubernetesAuthConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationConfig.
func (in *AuthenticationConfig) DeepCopy() *AuthenticationConfig {
	if in == nil {
		return nil
	}
	out := new(AuthenticationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationConfig) DeepCopyInto(out *AuthorizationConfig) {
	*out = *in
	if in.OpenFGA != nil {
		in, out := &in.OpenFGA, &out.OpenFGA
		*out = new(OpenFGAConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Cedar != nil {
		in, out := &in.Cedar, &out.Cedar
		*out = new(CedarConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationConfig.
func (in *AuthorizationConfig) DeepCopy() *AuthorizationConfig {
	if in == nil {
		return nil
	}
	out := new(AuthorizationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfig) DeepCopyInto(out *AzureConfig) {
	*out = *in
	if in.AllowManagedIdentity != nil {
		in, out := &in.AllowManagedIdentity, &out.AllowManagedIdentity
		*out = new(bool)
		**out = **in
	}
	if in.AllowWorkloadIdentity != nil {
		in, out := &in.AllowWorkloadIdentity, &out.AllowWorkloadIdentity
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfig.
func (in *AzureConfig) DeepCopy() *AzureConfig {
	if in == nil {
		return nil
	}
	out := new(AzureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapConfig) DeepCopyInto(out *BootstrapConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapConfig.
func (in *BootstrapConfig) DeepCopy() *BootstrapConfig {
	if in == nil {
		return nil
	}
	out := new(BootstrapConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CORSConfig) DeepCopyInto(out *CORSConfig) {
	*out = *in
	if in.AllowOrigins != nil {
		in, out := &in.AllowOrigins, &out.AllowOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowHeaders != nil {
		in, out := &in.AllowHeaders, &out.AllowHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowMethods != nil {
		in, out := &in.AllowMethods, &out.AllowMethods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CORSConfig.
func (in *CORSConfig) DeepCopy() *CORSConfig {
	if in == nil {
		return nil
	}
	out := new(CORSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CedarConfig) DeepCopyInto(out *CedarConfig) {
	*out = *in
	if in.UserDerivations != nil {
		in, out := &in.UserDerivations, &out.UserDerivations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CedarConfig.
func (in *CedarConfig) DeepCopy() *CedarConfig {
	if in == nil {
		return nil
	}
	out := new(CedarConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfig) DeepCopyInto(out *DatabaseConfig) {
	*out = *in
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfig.
func (in *DatabaseConfig) DeepCopy() *DatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPConfig) DeepCopyInto(out *GCPConfig) {
	*out = *in
	if in.AllowWorkloadIdentity != nil {
		in, out := &in.AllowWorkloadIdentity, &out.AllowWorkloadIdentity
		*out = new(bool)
		**out = **in
	}
	if in.AllowServiceAccountKey != nil {
		in, out := &in.AllowServiceAccountKey, &out.AllowServiceAccountKey
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPConfig.
func (in *GCPConfig) DeepCopy() *GCPConfig {
	if in == nil {
		return nil
	}
	out := new(GCPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdempotencyConfig) DeepCopyInto(out *IdempotencyConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Lifetime != nil {
		in, out := &in.Lifetime, &out.Lifetime
		*out = new(string)
		**out = **in
	}
	if in.GracePeriod != nil {
		in, out := &in.GracePeriod, &out.GracePeriod
		*out = new(string)
		**out = **in
	}
	if in.CleanupTimeout != nil {
		in, out := &in.CleanupTimeout, &out.CleanupTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdempotencyConfig.
func (in *IdempotencyConfig) DeepCopy() *IdempotencyConfig {
	if in == nil {
		return nil
	}
	out := new(IdempotencyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesAuthConfig) DeepCopyInto(out *KubernetesAuthConfig) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AcceptLegacyTokens != nil {
		in, out := &in.AcceptLegacyTokens, &out.AcceptLegacyTokens
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesAuthConfig.
func (in *KubernetesAuthConfig) DeepCopy() *KubernetesAuthConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Lakekeeper) DeepCopyInto(out *Lakekeeper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Lakekeeper.
func (in *Lakekeeper) DeepCopy() *Lakekeeper {
	if in == nil {
		return nil
	}
	out := new(Lakekeeper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Lakekeeper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakekeeperList) DeepCopyInto(out *LakekeeperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Lakekeeper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakekeeperList.
func (in *LakekeeperList) DeepCopy() *LakekeeperList {
	if in == nil {
		return nil
	}
	out := new(LakekeeperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LakekeeperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakekeeperSpec) DeepCopyInto(out *LakekeeperSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	in.Database.DeepCopyInto(&out.Database)
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(ServerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretStore != nil {
		in, out := &in.SecretStore, &out.SecretStore
		*out = new(SecretStoreConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(AuthenticationConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Authorization.DeepCopyInto(&out.Authorization)
	if in.Idempotency != nil {
		in, out := &in.Idempotency, &out.Idempotency
		*out = new(IdempotencyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TaskQueues != nil {
		in, out := &in.TaskQueues, &out.TaskQueues
		*out = new(TaskQueuesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestLimits != nil {
		in, out := &in.RequestLimits, &out.RequestLimits
		*out = new(RequestLimitsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(SSLConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Bootstrap != nil {
		in, out := &in.Bootstrap, &out.Bootstrap
		*out = new(BootstrapConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakekeeperSpec.
func (in *LakekeeperSpec) DeepCopy() *LakekeeperSpec {
	if in == nil {
		return nil
	}
	out := new(LakekeeperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakekeeperStatus) DeepCopyInto(out *LakekeeperStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BootstrappedAt != nil {
		in, out := &in.BootstrappedAt, &out.BootstrappedAt
		*out = (*in).DeepCopy()
	}
	if in.ServerID != nil {
		in, out := &in.ServerID, &out.ServerID
		*out = new(string)
		**out = **in
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.ReadyReplicas != nil {
		in, out := &in.ReadyReplicas, &out.ReadyReplicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakekeeperStatus.
func (in *LakekeeperStatus) DeepCopy() *LakekeeperStatus {
	if in == nil {
		return nil
	}
	out := new(LakekeeperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenFGAConfig) DeepCopyInto(out *OpenFGAConfig) {
	*out = *in
	if in.AuthorizationModelVersion != nil {
		in, out := &in.AuthorizationModelVersion, &out.AuthorizationModelVersion
		*out = new(string)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenFGAConfig.
func (in *OpenFGAConfig) DeepCopy() *OpenFGAConfig {
	if in == nil {
		return nil
	}
	out := new(OpenFGAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenIDConfig) DeepCopyInto(out *OpenIDConfig) {
	*out = *in
	if in.SubjectClaim != nil {
		in, out := &in.SubjectClaim, &out.SubjectClaim
		*out = new(string)
		**out = **in
	}
	if in.RolesClaim != nil {
		in, out := &in.RolesClaim, &out.RolesClaim
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenIDConfig.
func (in *OpenIDConfig) DeepCopy() *OpenIDConfig {
	if in == nil {
		return nil
	}
	out := new(OpenIDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaginationConfig) DeepCopyInto(out *PaginationConfig) {
	*out = *in
	if in.DefaultSize != nil {
		in, out := &in.DefaultSize, &out.DefaultSize
		*out = new(int32)
		**out = **in
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaginationConfig.
func (in *PaginationConfig) DeepCopy() *PaginationConfig {
	if in == nil {
		return nil
	}
	out := new(PaginationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresConfig) DeepCopyInto(out *PostgresConfig) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
	if in.UserSecretRef != nil {
		in, out := &in.UserSecretRef, &out.UserSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	in.PasswordSecretRef.DeepCopyInto(&out.PasswordSecretRef)
	in.EncryptionKeySecretRef.DeepCopyInto(&out.EncryptionKeySecretRef)
	if in.ReadHost != nil {
		in, out := &in.ReadHost, &out.ReadHost
		*out = new(string)
		**out = **in
	}
	if in.MaxConnections != nil {
		in, out := &in.MaxConnections, &out.MaxConnections
		*out = new(int32)
		**out = **in
	}
	if in.MinIdleConnections != nil {
		in, out := &in.MinIdleConnections, &out.MinIdleConnections
		*out = new(int32)
		**out = **in
	}
	if in.ConnectionTimeout != nil {
		in, out := &in.ConnectionTimeout, &out.ConnectionTimeout
		*out = new(string)
		**out = **in
	}
	if in.SSLMode != nil {
		in, out := &in.SSLMode, &out.SSLMode
		*out = new(string)
		**out = **in
	}
	if in.SSLRootCertSecretRef != nil {
		in, out := &in.SSLRootCertSecretRef, &out.SSLRootCertSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresConfig.
func (in *PostgresConfig) DeepCopy() *PostgresConfig {
	if in == nil {
		return nil
	}
	out := new(PostgresConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestLimitsConfig) DeepCopyInto(out *RequestLimitsConfig) {
	*out = *in
	if in.MaxRequestBodySize != nil {
		in, out := &in.MaxRequestBodySize, &out.MaxRequestBodySize
		*out = new(string)
		**out = **in
	}
	if in.MaxRequestTime != nil {
		in, out := &in.MaxRequestTime, &out.MaxRequestTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestLimitsConfig.
func (in *RequestLimitsConfig) DeepCopy() *RequestLimitsConfig {
	if in == nil {
		return nil
	}
	out := new(RequestLimitsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLConfig) DeepCopyInto(out *SSLConfig) {
	*out = *in
	if in.CertFileSecretRef != nil {
		in, out := &in.CertFileSecretRef, &out.CertFileSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.CertDirConfigMapRef != nil {
		in, out := &in.CertDirConfigMapRef, &out.CertDirConfigMapRef
		*out = new(v1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLConfig.
func (in *SSLConfig) DeepCopy() *SSLConfig {
	if in == nil {
		return nil
	}
	out := new(SSLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStoreConfig) DeepCopyInto(out *SecretStoreConfig) {
	*out = *in
	if in.VaultKV2 != nil {
		in, out := &in.VaultKV2, &out.VaultKV2
		*out = new(VaultKV2Config)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStoreConfig.
func (in *SecretStoreConfig) DeepCopy() *SecretStoreConfig {
	if in == nil {
		return nil
	}
	out := new(SecretStoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerConfig) DeepCopyInto(out *ServerConfig) {
	*out = *in
	if in.BaseURI != nil {
		in, out := &in.BaseURI, &out.BaseURI
		*out = new(string)
		**out = **in
	}
	if in.ListenPort != nil {
		in, out := &in.ListenPort, &out.ListenPort
		*out = new(int32)
		**out = **in
	}
	if in.MetricsPort != nil {
		in, out := &in.MetricsPort, &out.MetricsPort
		*out = new(int32)
		**out = **in
	}
	if in.EnableDefaultProject != nil {
		in, out := &in.EnableDefaultProject, &out.EnableDefaultProject
		*out = new(bool)
		**out = **in
	}
	if in.Pagination != nil {
		in, out := &in.Pagination, &out.Pagination
		*out = new(PaginationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CORS != nil {
		in, out := &in.CORS, &out.CORS
		*out = new(CORSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ReservedNamespaces != nil {
		in, out := &in.ReservedNamespaces, &out.ReservedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StorageSystemCredentials != nil {
		in, out := &in.StorageSystemCredentials, &out.StorageSystemCredentials
		*out = new(StorageSystemCredentialsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerConfig.
func (in *ServerConfig) DeepCopy() *ServerConfig {
	if in == nil {
		return nil
	}
	out := new(ServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSystemCredentialsConfig) DeepCopyInto(out *StorageSystemCredentialsConfig) {
	*out = *in
	if in.EnableAWS != nil {
		in, out := &in.EnableAWS, &out.EnableAWS
		*out = new(bool)
		**out = **in
	}
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableAzure != nil {
		in, out := &in.EnableAzure, &out.EnableAzure
		*out = new(bool)
		**out = **in
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableGCP != nil {
		in, out := &in.EnableGCP, &out.EnableGCP
		*out = new(bool)
		**out = **in
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GCPConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSystemCredentialsConfig.
func (in *StorageSystemCredentialsConfig) DeepCopy() *StorageSystemCredentialsConfig {
	if in == nil {
		return nil
	}
	out := new(StorageSystemCredentialsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskQueuesConfig) DeepCopyInto(out *TaskQueuesConfig) {
	*out = *in
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(string)
		**out = **in
	}
	if in.TabularExpirationWorkers != nil {
		in, out := &in.TabularExpirationWorkers, &out.TabularExpirationWorkers
		*out = new(int32)
		**out = **in
	}
	if in.TabularPurgeWorkers != nil {
		in, out := &in.TabularPurgeWorkers, &out.TabularPurgeWorkers
		*out = new(int32)
		**out = **in
	}
	if in.ExpireSnapshotsWorkers != nil {
		in, out := &in.ExpireSnapshotsWorkers, &out.ExpireSnapshotsWorkers
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskQueuesConfig.
func (in *TaskQueuesConfig) DeepCopy() *TaskQueuesConfig {
	if in == nil {
		return nil
	}
	out := new(TaskQueuesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKV2Config) DeepCopyInto(out *VaultKV2Config) {
	*out = *in
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(string)
		**out = **in
	}
	if in.UserSecretRef != nil {
		in, out := &in.UserSecretRef, &out.UserSecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	in.PasswordSecretRef.DeepCopyInto(&out.PasswordSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKV2Config.
func (in *VaultKV2Config) DeepCopy() *VaultKV2Config {
	if in == nil {
		return nil
	}
	out := new(VaultKV2Config)
	in.DeepCopyInto(out)
	return out
}
