name: Docker Publish CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build-and-push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make docker-buildx
