name: Test Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'

    - name: Create Generated Files
      run: make manifests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Test Build
      run: make docker-build
